### ISSUE TITLE
How to install torchlight

### ISSUE THREAD

**Issue by Thangtran27** [KathPra/LSHR_LSHT#1]
I am setting up environment for running your code. But I can't install pip "install -e torchlight". Although, I installed torchlight by either `pip install torchlight==0.0.1` or downloaded file .zip into my computer, then cmd `install -e torchlight`, I run your code, the screen displayed: 
`Traceback (most recent call last):
File "FPHA/cpu_main.py", line 28, in <module>
from torchlight import DictAction
ImportError: cannot import name 'DictAction'`
How can I install this package?

**Comment by KathPra** [comment]
Hi!
I faced the same problems when I first installed these packages.
My solution was this:

```
cd ../graph/torchlight; python setup.py install
cd ../torchlight; python setup.py install
pip install -e torchlight
```

Hope this helps! Let me know, if you are facing other issue / have questions!
