### ISSUE TITLE
How to process data of FPHAB dataset

### ISSUE THREAD

**Issue by Thangtran27** [KathPra/LSHR_LSHT#2]
Could you tell me about code or some instructure for data processing of FPHAB dataset?
Thank you.

**Comment by Xuziqi-come** [comment]
> 您能告诉我有关FPHAB数据集数据处理的代码或一些结构吗？ 谢谢。

我也有这个问题，请问您处理好了吗？

**Comment by yunfan258** [comment]
我也遇到了这个问题，请问能否提供处理FPHAB数据集的代码吗?或者提供处理完的数据

**Comment by KathPra** [comment]
Hi! As described in the paper, the same preprocessing is used for both datasets. For your convenience, I have included the python code for the FPHA dataset in the repo.
